export const SET_RECONMEND = 'SET_RECONMEND'

export const SET_NEWSONG = 'SET_NEWSONG'

export const SET_NEWEST = 'SET_NEWEST'

export const SET_HOSTARTIST = 'SET_HOSTARTIST'

export const SET_TOPLIST = 'SET_TOPLIST'

export const SET_BANNER = 'SET_BANNER'

export const SET_PLAYLIST = 'SET_PLAYLIST'

export const SET_SONGURL = 'SET_SONGURL'

export const SET_CHECKMUSIC = 'SET_CHECKMUSIC'

export const SET_EMPTY = 'SET_EMPTY'

export const SET_CURRSONG = 'SET_CURRSONG'

export const SET_EMPTYSONGLIS = 'SET_EMPTYSONGLIS'

export const SET_CHANGLEAVE = 'SET_CHANGLEAVE'

export const SET_PLAYINGTRACKS = 'SET_PLAYINGTRACKS'

export const SET_PLAYINGMASSGE = 'SET_PLAYINGMASSGE'

export const SET_LYRIC = 'SET_LYRIC'

export const SET_PLAYLISTHOT = 'SET_PLAYLISTHOT'

export const SET_PLAYLISTALL = 'SET_PLAYLISTALL'

export const HEANDEL_PLAYLISTALL = 'HEANDEL_PLAYLISTALL'

export const SET_DISCOVERLIST = 'SET_DISCOVERLIST'

export const SET_ISDONELIST = 'SET_ISDONELIST'

export const SET_SHOWPLAYER = 'SET_SHOWPLAYER'

export const SET_USERCOOKIE = 'SET_USERCOOKIE'

export const SET_USERPLAYLIST = 'SET_USERPLAYLIST'

export const SET_LOVESONGLIST = 'SET_LOVESONGLIST'

export const IS_LOGIN = 'IS_LOGIN'

export const SET_SEARCHRESULT = 'SET_SEARCHRESULT'

